server.port=8080

# JWT Configuration
jwt.secret=c3VwZXJfc2VjcmV0X2tleV9mb3Jfand0X3NpZ25hdHVyZV90aGF0X211c3RfYmVfbG9uZw==
jwt.expiration=86400000

# Google OAuth
google.client.id=144988442790-lgpr83tmeng57n06p8ll2413u0igdamv.apps.googleusercontent.com

# MongoDB (default)
MONGODB_URI=mongodb+srv://thulanads_db_user:ajdaCsyDYEfKVHDu@unilife-cluster.vfl4q4i.mongodb.net/unilife
# Multipart configuration for file uploads
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

